# Generic makefile - Unix (hp) version
#
            LDLIBS = -lMrm -lXm  -lXt -lXmu -lX11
         LDOPTIONS = -L/usr/lib/Motif1.1 -L/usr/lib/X11R4
            CFLAGS = -O -Wp,-H200000 -D_NO_PROTO $(DEFINES) -I/usr/include/X11R4 -I/usr/include/Motif1.1 -I./
                RM = rm -f
               UIL = /usr/bin/X11/uil

include CommonMakefile

$(PGM):: $(OBJS) 
	$(RM) $@
	$(CC) -o $@ $(OBJS) $(LDOPTIONS) $(LDLIBS)



