#	Platform-specific Makefile for W3 Library	(decstation)
#	-----------------------------------------
#

WWW = ../..

#  Where should temporary (object) files go?
WTMP = /tmp


#CFLAGS = 
CFLAGS =  -Wall -g
CC = gcc
#LFLAGS = -lresolv
LFLAGS = 

ASIS_MACH = dec-station/ultrix-4.2
WWW_MACH = decstation

# Directory for installed binary:
LIBDIR = /usr/local/lib

