/*
 * biop.h
 */
int biOp();

void convError();
void int2float();
void int2str();
void char2int();
void char2float();
void char2str();
void float2str();
void float2int();
void str2int();
void str2float();

void char_plus();
void float_plus();
void str_plus();
void int_plus();
void int_minus();
void int_mod();
void char_minus();
void float_minus();
void str_minus();
void char_mod();
void float_mod();
void str_mod();
void int_mult();
void char_mult();
void float_mult();
void str_mult();
void int_div();
void char_div();
void float_div();
void str_div();
void int_eq();
void char_eq();
void float_eq();
void str_eq();
void int_ne();
void char_ne();
void float_ne();
void str_ne();
void int_lt();
void char_lt();
void float_lt();
void str_lt();
void int_le();
void char_le();
void float_le();
void str_le();
void int_gt();
void char_gt();
void float_gt();
void str_gt();
void int_ge();
void char_ge();
void float_ge();
void str_ge();
void int_and();
void char_and();
void float_and();
void str_and();
void int_or();
void char_or();
void float_or();
void str_or();

